### ISSUE TITLE
UX little improvement proposal

### ISSUE THREAD

**Issue by josep11** [samschott/maestral-cocoa#21]
Grey out "Show Sync Issues" button when no sync issues are found

https://user-images.githubusercontent.com/5558911/140280178-fa2f160f-c64d-4ae6-8f79-a5e82b27fe89.mov

**Comment by SamSchott** [comment]
I like the idea :) Fancy submitting a PR for this? The correct place to do this would probably be:

https://github.com/SamSchott/maestral-cocoa/blob/f43c17d1a48bbfb6811f7c0af0abae12eba7e470/src/maestral_cocoa/app.py#L368-L371

**Comment by josep11** [comment]
> I like the idea :) Fancy submitting a PR for this? The correct place to do this would probably be:
> 
> https://github.com/SamSchott/maestral-cocoa/blob/f43c17d1a48bbfb6811f7c0af0abae12eba7e470/src/maestral_cocoa/app.py#L368-L371

Well, at the moment I don't have xcode nor the latest version of Mac OS X. That's why I submitted a proposal instead of a PR.
