### ISSUE TITLE
Please provide build instructions

### ISSUE THREAD

**Issue by derreisende77** [samschott/maestral-cocoa#27]
Could you please provide setup instructions in order to get a working build for the cocoa app?
I would love to provide a PR for issue #21 but I would like to test it before submitting.

Unfortunately I am no regular python coder (coming from a C/C++ an Java background on macOS) and on my Apple Silicon the Xcode build just fails with "Build cancelled" 😞 
Therefore any setup instructions would be highly appreciated.

**Comment by samschott** [comment]
Interesting, the build runs just fine on GitHub Actions but on my own PC Xcode also cancels the build, apparently with no reason.

I suspect that this is a side-effect of running `agvtool` during each build to auto-increment the build number. This step modifies the Xcode project itself which likely causes the build to be canceled. Moving this to be the last step in the build process seems to fix all issues.

**Comment by samschott** [comment]
A few more details about the build process: Building is as simple simple as opening the Xcode project and building the project - or at least it should be. However, the Xcode project contains its own copy of the Python code. I typically use the build tool [briefcase](www.github.com/beeware/briefcase) run the build process in separate steps:

1. Run `briefcase update macOS Xcode -r -d` to update the Python code, both from maestral-cocoa and all 3rd party dependencies.
2. Build the Xcode project with `briefcase build macOS Xcode`. This is the equivalent to building from the Xcode GUI.
3. Run post-build scripts to replace `.py` with `.pyc` files (this saves a bit of space) and to copy over the CLI entry point.
4. Run `briefcase package macOS Xcode` to sign and package the app bundle as a DMG.
5. Notarise the DMG.

The exact steps can be found in `.github/actions/build.yaml`.

Note that the Python code is not actually compiled, rather the main executable includes a statically Python interpreter and runs the proper entry point of the Python package.

To test code changes, it will be easier to modify the Python code in `src/maestral_coaoa` and install it with `pip3 install .` The pip-install will also install the command line entry point in your PATH, in my case at `/Library/Frameworks/Python.framework/Versions/3.10/bin/`. You can then run `maestral gui` to launch the just installed GUI with all your modifications.

**Comment by derreisende77** [comment]
Sorry for the late reply but now building and running via Xcode works :) However, modifying Code Signing Options for automatic management causes the build to fail again:
```
CodeSign /Users/XXX/Downloads/test/maestral-cocoa/macOS/Xcode/Maestral/DerivedData/Maestral/Build/Products/Debug/Maestral.app (in target 'Maestral' from project 'Maestral')
    cd /Users/XXX/Downloads/test/maestral-cocoa/macOS/Xcode/Maestral
    export CODESIGN_ALLOCATE\=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    
    Signing Identity:     "-"
    
    /usr/bin/codesign --force --sign - -o runtime --entitlements /Users/XXX/Downloads/test/maestral-cocoa/macOS/Xcode/Maestral/DerivedData/Maestral/Build/Intermediates.noindex/Maestral.build/Debug/Maestral.build/Maestral.app.xcent --timestamp\=none --generate-entitlement-der /Users/XXX/Downloads/test/maestral-cocoa/macOS/Xcode/Maestral/DerivedData/Maestral/Build/Products/Debug/Maestral.app

/Users/XXX/Downloads/test/maestral-cocoa/macOS/Xcode/Maestral/DerivedData/Maestral/Build/Products/Debug/Maestral.app: code object is not signed at all
In subcomponent: /Users/XXX/Downloads/test/maestral-cocoa/macOS/Xcode/Maestral/DerivedData/Maestral/Build/Products/Debug/Maestral.app/Contents/MacOS/maestral-cli
```

From my interpretation this is caused somehow by `maestral-cli`?

But for now I can try and test the necessary changes I want to commit.

**Comment by samschott** [comment]
Uh, did you run the codesign command manually or through Xcode? I can see a few difference to how briefcase runs the codesigning tool but only a few stand out which could cause problems:

1. The use of `--timestamp\=none`. According to the man page, if omitted , a not specified "system-specific default behavior is invoked".
2. The `--entitlements` option does not point to the the `maestral-cocoa.entitlements` file.
3. Briefcase uses the `--deep` option:

   > When signing a bundle, specifies that nested code content such as helpers, frameworks, and plug-ins, should be recursively signed in turn.

    This is required to sign the Sparkle framework and `maestral-cli`.

From the error message, my bet is on the latter causing problems.

**Comment by derreisende77** [comment]
I changed the project settings in Xcode. I would prefer not to install additional python stuff on my MBP as I won‘t really use it in the future.

**Comment by quantumDavey** [comment]
@derreisende77 

Hi, I just found your fork of maestral-cocoa, with the xcode proj source in it - so I guess I'm a bit closer ! Are there any notes on building, or is there any advice you would have on building it ?

**Comment by samschott** [comment]
The build instruction from https://github.com/samschott/maestral-cocoa/issues/27#issuecomment-1006114364 are bit out of date now. You essentially want to follow the build process that is also used by the GitHub Actions https://github.com/samschott/maestral-cocoa/blob/main/.github/workflows/build.yml, minus some accommodation to set up the action runner environment:

```
# Install the briefcase build tool.
# See https://github.com/beeware/briefcase.
pip3 install -U briefcase

# Clone maestral-cocoa and navigate to directory.
git clone https://github.com/samschott/maestral-cocoa.git
cd maestral-cocoa

# Set up an Xcode project with a bundled Python distribution
# and all Python packages required to run Maestral.
briefcase create macOS Xcode

# Build the Xcode project
briefcase build macOS Xcode

# Sign Maestral, package it as a dmg and notarize the binary.
# If you don't have an Apple developer account, the app will
# be ad-hoc signed. Note that this step is required to run
# Maestral, because the bundled Sparkle updater would otherwise
# fail Library validation at startup.
briefcase package macOS Xcode
```

**Comment by samschott** [comment]
Marking this as closed, but feel free to comment if there any remaining questions.
